name: Deploy Flask app

on:
  workflow_call:

jobs:
  deploy:
    env:
      DOCKERHUB_USER: ${{vars.DOCKERHUB_USER}}

    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: connect form SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install docker.io docker-compose-v2 -y
            sudo usermod -aG docker $USER
            #newgrp
            mkdir devops

     # - name: Deploy with docker compose 
     #    docker compose down
     #     docker compose up -d --build --force-recreate 

