# Dockerfile scan with hadolint 

name: Dockerfile Scan

on:
  workflow_call:

jobs:
  dockerfile_scan:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: Scan Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile