# name of workflow
name: pyhton lint 

# set trigger point
on:
  push:
    branches: [main]

# put actual action inside jod and steps
jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup the pyhton 
        uses: actions/setup-python@v4
        with:
          pyhton_version: "3.14"

      - name: install requirements
        run: pip install -r requirements.txt

      - name: flake8 linting
        run: flake8 run.py

